type LabelSet = Record<string, string>;

function normalizeLabels(labels: LabelSet): string {
  return Object.entries(labels)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `${key}="${String(value).replace(/"/g, '\\"')}"`)
    .join(',');
}

class CounterMetric {
  constructor(
    readonly name: string,
    readonly help: string,
    readonly labelNames: string[] = [],
  ) {}

  private readonly values = new Map<string, number>();

  inc(labels: LabelSet = {}, value = 1): void {
    const key = normalizeLabels(labels);
    this.values.set(key, (this.values.get(key) ?? 0) + value);
  }

  render(): string[] {
    const lines = [`# HELP ${this.name} ${this.help}`, `# TYPE ${this.name} counter`];

    for (const [labelKey, value] of this.values.entries()) {
      const suffix = labelKey ? `{${labelKey}}` : '';
      lines.push(`${this.name}${suffix} ${value}`);
    }

    if (this.values.size === 0) {
      lines.push(`${this.name} 0`);
    }

    return lines;
  }
}

class HistogramMetric {
  private readonly bucketValues = new Map<string, number[]>();
  private readonly sumValues = new Map<string, number>();
  private readonly countValues = new Map<string, number>();

  constructor(
    readonly name: string,
    readonly help: string,
    private readonly buckets: number[],
    readonly labelNames: string[] = [],
  ) {}

  observe(labels: LabelSet = {}, value: number): void {
    const key = normalizeLabels(labels);
    const counts = this.bucketValues.get(key) ?? this.buckets.map(() => 0);

    this.buckets.forEach((bucket, index) => {
      if (value <= bucket) {
        counts[index] += 1;
      }
    });

    this.bucketValues.set(key, counts);
    this.sumValues.set(key, (this.sumValues.get(key) ?? 0) + value);
    this.countValues.set(key, (this.countValues.get(key) ?? 0) + 1);
  }

  render(): string[] {
    const lines = [`# HELP ${this.name} ${this.help}`, `# TYPE ${this.name} histogram`];
    const labelKeys = Array.from(
      new Set([
        ...this.bucketValues.keys(),
        ...this.sumValues.keys(),
        ...this.countValues.keys(),
      ]),
    );

    if (labelKeys.length === 0) {
      labelKeys.push('');
    }

    for (const labelKey of labelKeys) {
      const counts = this.bucketValues.get(labelKey) ?? this.buckets.map(() => 0);
      this.buckets.forEach((bucket, index) => {
        const labels = [labelKey, `le="${bucket}"`].filter(Boolean).join(',');
        lines.push(`${this.name}_bucket{${labels}} ${counts[index] ?? 0}`);
      });

      const infLabels = [labelKey, 'le="+Inf"'].filter(Boolean).join(',');
      const count = this.countValues.get(labelKey) ?? 0;
      const sum = this.sumValues.get(labelKey) ?? 0;
      lines.push(`${this.name}_bucket{${infLabels}} ${count}`);
      const suffix = labelKey ? `{${labelKey}}` : '';
      lines.push(`${this.name}_sum${suffix} ${sum}`);
      lines.push(`${this.name}_count${suffix} ${count}`);
    }

    return lines;
  }
}

class MetricsRegistry {
  private readonly counters = new Map<string, CounterMetric>();
  private readonly histograms = new Map<string, HistogramMetric>();

  counter(name: string, help: string, labelNames: string[] = []): CounterMetric {
    if (!this.counters.has(name)) {
      this.counters.set(name, new CounterMetric(name, help, labelNames));
    }

    return this.counters.get(name)!;
  }

  histogram(
    name: string,
    help: string,
    buckets: number[],
    labelNames: string[] = [],
  ): HistogramMetric {
    if (!this.histograms.has(name)) {
      this.histograms.set(name, new HistogramMetric(name, help, buckets, labelNames));
    }

    return this.histograms.get(name)!;
  }

  render(): string {
    const lines = ['# Generated by Aura recommendation metrics registry'];

    this.counters.forEach((metric) => lines.push(...metric.render()));
    this.histograms.forEach((metric) => lines.push(...metric.render()));

    return `${lines.join('\n')}\n`;
  }
}

export const metricsRegistry = new MetricsRegistry();

