import { User } from '../../entities/user/user.entity';
import { Email } from '../../entities/value-object/email.vo';
import { RegisterCommand, RegisterResult } from '../dto';
import { EmailAlreadyExistsError, RateLimitExceededError } from '../errors';
import {
  IEmailSender,
  IEmailVerificationTokenRepository,
  IPasswordHasher,
  IRateLimiter,
  ITokenGenerator,
  IUserRepository,
  EmailVerificationToken,
} from '../ports';
import { IRegisterUseCase } from '../ports/input/register.usecase';

/**
 * Use Case: Register new user with email and password
 */
export class RegisterUseCase implements IRegisterUseCase {
  constructor(
    private readonly userRepository: IUserRepository,
    private readonly passwordHasher: IPasswordHasher,
    private readonly rateLimiter: IRateLimiter,
    private readonly tokenGenerator: ITokenGenerator,
    private readonly emailVerificationTokenRepository: IEmailVerificationTokenRepository,
    private readonly emailSender: IEmailSender,
    private readonly ipAddress?: string, // Injected from controller
  ) {}

  async execute(command: RegisterCommand): Promise<RegisterResult> {
    const { email: emailString, password } = command;

    // STEP 2: Rate Limit Check (Redis)
    await this.checkRateLimit(emailString);

    // STEP 3 & 5: Hash password and create user
    // Note: We don't check for existing user here - let DB unique constraint handle it
    const hashedPassword = await this.passwordHasher.hash(password);

    // Create Email value object (this will validate email format)
    const email = new Email(emailString);

    // Create User entity using static factory method
    const user = User.registerWithEmail(email, hashedPassword);

    try {
      // STEP 5: Insert User (MySQL transaction handles uniqueness)
      const savedUser = await this.userRepository.save(user);

      // STEP 6: Create Email Verification Token
      const rawToken = this.tokenGenerator.generateRandomToken(32); // 256-bit
      const tokenHash = this.tokenGenerator.hashToken(rawToken);
      const expiresAt = new Date(Date.now() + 30 * 60 * 1000); // 30 minutes

      const emailVerificationToken: EmailVerificationToken = {
        id: '', // Will be generated by repository
        userId: savedUser.id!,
        tokenHash,
        expiresAt,
        createdAt: new Date(),
      };

      await this.emailVerificationTokenRepository.save(emailVerificationToken);

      // STEP 7: Send Email Verification
      await this.emailSender.sendEmailVerification(emailString, rawToken);

      // STEP 8: Response
      return {
        message: 'Registration successful. Please verify your email.',
      };
    } catch (error: any) {
      // STEP 5: Handle duplicate email error from database
      if (this.isDuplicateEmailError(error)) {
        throw new EmailAlreadyExistsError();
      }
      throw error;
    }
  }

  private async checkRateLimit(email: string): Promise<void> {
    // Check IP rate limit
    if (this.ipAddress) {
      const isIpLimited = await this.rateLimiter.isRegisterRateLimitExceeded(this.ipAddress);
      if (isIpLimited) {
        throw new RateLimitExceededError();
      }
      await this.rateLimiter.incrementRegisterRateLimit(this.ipAddress);
    }

    // Check email rate limit
    const isEmailLimited = await this.rateLimiter.isRegisterEmailRateLimitExceeded(email);
    if (isEmailLimited) {
      throw new RateLimitExceededError();
    }
    await this.rateLimiter.incrementRegisterEmailRateLimit(email);
  }

  private isDuplicateEmailError(error: any): boolean {
    // MySQL duplicate entry error code
    return (
      error.code === 'ER_DUP_ENTRY' ||
      error.code === 23000 ||
      (error.message && error.message.includes('Duplicate entry'))
    );
  }
}