### Remove Cart Item - Success
DELETE http://localhost:5000/api/cart/items/{{cartItemId}}
Authorization: Bearer {{accessToken}}

###

### Remove Cart Item - Not Found
DELETE http://localhost:5000/api/cart/items/00000000-0000-0000-0000-000000000000
Authorization: Bearer {{accessToken}}

###
