ALTER TABLE `orders`
  MODIFY `status` ENUM(
    'PENDING', 'CONFIRMED', 'PAID', 'PACKING', 'AWAITING_PICKUP',
    'SHIPPED', 'DELIVERING', 'DELIVERY_FAILED', 'LOST', 'RETURN_TO_STORE',
    'DELIVERED', 'COMPLETED', 'CANCELLED', 'RETURNED'
  ) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `order_status_history`
  MODIFY `old_status` ENUM(
    'PENDING', 'CONFIRMED', 'PAID', 'PACKING', 'AWAITING_PICKUP',
    'SHIPPED', 'DELIVERING', 'DELIVERY_FAILED', 'LOST', 'RETURN_TO_STORE',
    'DELIVERED', 'COMPLETED', 'CANCELLED', 'RETURNED'
  ) NULL,
  MODIFY `new_status` ENUM(
    'PENDING', 'CONFIRMED', 'PAID', 'PACKING', 'AWAITING_PICKUP',
    'SHIPPED', 'DELIVERING', 'DELIVERY_FAILED', 'LOST', 'RETURN_TO_STORE',
    'DELIVERED', 'COMPLETED', 'CANCELLED', 'RETURNED'
  ) NOT NULL;
