-- AlterTable
ALTER TABLE `orders` MODIFY `return_status` ENUM('REQUESTED', 'APPROVED', 'WAITING_PICKUP', 'SHIPPING', 'RETURNING', 'COMPLETED', 'REJECTED') NULL;

-- AlterTable
ALTER TABLE `payment_transactions` MODIFY `status` ENUM('PENDING', 'PAID', 'FAILED', 'EXPIRED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `payments` MODIFY `status` ENUM('PENDING', 'PAID', 'SUCCESS', 'FAILED', 'EXPIRED', 'REFUNDED') NOT NULL DEFAULT 'PENDING';
