-- Phase 2: explicit fulfilment/COD states and transition reason.
ALTER TABLE `orders` MODIFY COLUMN `status`
  ENUM('PENDING','CONFIRMED','PAID','PACKING','SHIPPED','DELIVERY_FAILED','RETURN_TO_STORE','DELIVERED','COMPLETED','CANCELLED','RETURNED')
  NOT NULL DEFAULT 'PENDING';
ALTER TABLE `order_status_history` MODIFY COLUMN `old_status`
  ENUM('PENDING','CONFIRMED','PAID','PACKING','SHIPPED','DELIVERY_FAILED','RETURN_TO_STORE','DELIVERED','COMPLETED','CANCELLED','RETURNED') NULL;
ALTER TABLE `order_status_history` MODIFY COLUMN `new_status`
  ENUM('PENDING','CONFIRMED','PAID','PACKING','SHIPPED','DELIVERY_FAILED','RETURN_TO_STORE','DELIVERED','COMPLETED','CANCELLED','RETURNED') NOT NULL;
ALTER TABLE `order_status_history` ADD COLUMN `reason` VARCHAR(500) NULL;

